### ISSUE TITLE
"yarn startWebpackServer" error

### ISSUE THREAD

**Issue by marcopiani** [owid/owid-grapher#1078]
Hi,

I have tried to install a local version of the grapher.

I may have done mistakes on the way, but it feels I am almost there. I can log in, but

yarn startWebpackServer

gives me an error (see below). Any easy fix / anything obvious that I am doing / I have done wrong?

Thank you!

Marco

PS I had hoped I could experiment with this, but I know you are all busy, so by all means do not waste time on this issue if it what is wrong and how to fix it is not immediately clear

---

```
yarn run v1.22.15
$ webpack-dev-server --no-live-reload --config ./itsJustJavascript/webpack.config.js
[webpack-cli] ValidationError: Invalid options object. Ignore Plugin has been initialized using an options object that does not match the API schema.
 - options should be one of these:
   object { resourceRegExp, contextRegExp? } | object { checkResource }
   Details:
    * options misses the property 'resourceRegExp'. Should be:
      RegExp
      -> A RegExp to test the request against.
    * options misses the property 'checkResource'. Should be:
      function
      -> A filter function for resource and context.
    at validate (C:\Users\marco\OneDrive\Programming\owid\owid-grapher\node_modules\webpack\node_modules\schema-utils\dist\validate.js:105:11)
    at C:\Users\marco\OneDrive\Programming\owid\owid-grapher\node_modules\webpack\lib\util\create-schema-validation.js:16:17
    at new IgnorePlugin (C:\Users\marco\OneDrive\Programming\owid\owid-grapher\node_modules\webpack\lib\IgnorePlugin.js:28:3)
    at C:\Users\marco\OneDrive\Programming\owid\owid-grapher\itsJustJavascript\webpack.config.js:115:13
    at Generator.next (<anonymous>)
    at C:\Users\marco\OneDrive\Programming\owid\owid-grapher\itsJustJavascript\webpack.config.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\marco\OneDrive\Programming\owid\owid-grapher\itsJustJavascript\webpack.config.js:4:12)
    at config (C:\Users\marco\OneDrive\Programming\owid\owid-grapher\itsJustJavascript\webpack.config.js:23:31)
    at loadConfigByPath (C:\Users\marco\OneDrive\Programming\owid\owid-grapher\node_modules\webpack-cli\lib\webpack-cli.js:1745:27) {
  errors: [
    {
      keyword: 'anyOf',
      dataPath: '',
      schemaPath: '#/anyOf',
      params: {},
      message: 'should match some schema in anyOf',
      schema: [Array],
      parentSchema: [Object],
      data: /settings\/(serverSettings|clientSettingsReader)/,
      children: [Array]
    }
  ],
  schema: { title: 'IgnorePluginOptions', anyOf: [ [Object], [Object] ] },
  headerName: 'Ignore Plugin',
  baseDataPath: 'options',
  postFormatter: null
}
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
![Screenshot 2022-01-22 065409](https://user-images.githubusercontent.com/18381804/150637513-bb48ae43-e043-46bc-9fb7-c07b3314d1a5.png)

**Comment by danyx23** [comment]
Hi @marcopiani! 

Can you give a bit more info? What platform are you running this on? Did you follow the steps in the readme using nvm or did you run this another way? If another way, what is your node version?

BTW: We are about to simplify the repository structure to make external contributions easier - in about 4 weeks time it will hopefully be easier to navigate and set up a dev environment for grapher.

**Comment by danyx23** [comment]
I guess this is resolved?
