### ISSUE TITLE
499 Client Error fetching data from S3 during bake

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#2352]
Reported by @ikesau, this has happened on multiple staging builds, causing them to fail.

The error looks like this:

```
Error: Error fetching data from S3 for https://api.ourworldindata.org/v1/indicators/418749.data.json: 499 Client Error
  | at fetchS3ValuesByPath (/home/owid/owid-grapher/db/model/Variable.ts:499:15)
  | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  | at getVariableData (/home/owid/owid-grapher/db/model/Variable.ts:83:18)
  | at <anonymous> (/home/owid/owid-grapher/db/model/Variable.ts:213:23)
  | at async Promise.all (index 2)
  | at getDataForMultipleVariables (/home/owid/owid-grapher/db/model/Variable.ts:215:41)
  | at bakeGrapherToSvg (/home/owid/owid-grapher/baker/GrapherImageBaker.tsx:103:21)
  | at async Promise.all (index 2)
  | at bakeGrapherUrls (/home/owid/owid-grapher/baker/GrapherBakingUtils.ts:85:13)
  | at SiteBaker.bakeEmbeds (/home/owid/owid-grapher/baker/SiteBaker.tsx:155:9)
```

**Comment by larsyencken** [comment]
Marking this as "wontfix". We think this is a form of rate-limiting from CloudFlare perhaps, or it could be an issue just on the server. We've now switched to client side fetches from the API directly, so soon we'll stop baking this route completely.
