### ISSUE TITLE
Failures during baking when fetching images from Google Drive

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#2445]
We're getting exceptions like this during baking:

```
TypeError: fetch failed
  | at Object.fetch (node:internal/deps/undici/undici:11457:11)
  | at processTicksAndRejections (node:internal/process/task_queues:95:5)
  | at runNextTicks (node:internal/process/task_queues:64:3)
  | at process.processImmediate (node:internal/timers:447:9)
  | at async Promise.all (index 139)
  | at SiteBaker.bakeDriveImages (/home/owid/live/baker/SiteBaker.tsx:590:9)
  | at SiteBaker._bakeNonWordpressPages (/home/owid/live/baker/SiteBaker.tsx:702:9)
  | at SiteBaker.bakeAll (/home/owid/live/baker/SiteBaker.tsx:724:9)
  | at bake (/home/owid/live/baker/DeployUtils.ts:59:9) {
  | cause: ConnectTimeoutError: Connect Timeout Error
  | at onConnectTimeout (node:internal/deps/undici/undici:8422:28)
  | at node:internal/deps/undici/undici:8380:50
  | at Immediate._onImmediate (node:internal/deps/undici/undici:8411:13)
  | at process.processImmediate (node:internal/timers:476:21) {
  | code: 'UND_ERR_CONNECT_TIMEOUT'
  | }
  | }
  | Bugsnag.notify() was called before Bugsnag.start()
  | node:internal/process/promises:261
  | triggerUncaughtException(err, true /* fromPromise */);
  | ^
  |  
  | TypeError: fetch failed
  | at Object.fetch (node:internal/deps/undici/undici:11457:11)
  | at processTicksAndRejections (node:internal/process/task_queues:95:5)
  | at runNextTicks (node:internal/process/task_queues:64:3)
  | at process.processImmediate (node:internal/timers:447:9)
  | at async Promise.all (index 139)
  | at SiteBaker.bakeDriveImages (/home/owid/live/baker/SiteBaker.tsx:590:9)
  | at SiteBaker._bakeNonWordpressPages (/home/owid/live/baker/SiteBaker.tsx:702:9)
  | at SiteBaker.bakeAll (/home/owid/live/baker/SiteBaker.tsx:724:9)
  | at bake (/home/owid/live/baker/DeployUtils.ts:59:9) {
  | cause: ConnectTimeoutError: Connect Timeout Error
  | at onConnectTimeout (node:internal/deps/undici/undici:8422:28)
  | at node:internal/deps/undici/undici:8380:50
  | at Immediate._onImmediate (node:internal/deps/undici/undici:8411:13)
  | at process.processImmediate (node:internal/timers:476:21) {
  | code: 'UND_ERR_CONNECT_TIMEOUT'
  | }
  | }
 ```

**Comment by larsyencken** [comment]
Hopefully fixed by: https://github.com/owid/owid-grapher/pull/2446

**Comment by Marigold** [comment]
@ikesau I'm still running into the same error with batch size 10. Can we lower it down to batch size 2? (It worked every time for me and has negligible impact on performance)

**Comment by ikesau** [comment]
Just pushed! Let's see how it goes 🙂

**Comment by ikesau** [comment]
We aren't encountering this anymore, though we would still like to improve our image pipeline soon with Cloudflare Images
