### ISSUE TITLE
Can't approve a Chart Sync migration in the Chart approval tool

### ISSUE THREAD

**Issue by paarriagadap** [owid/owid-grapher#3479]
## Description

After using Chart Sync, I can't approve a series of charts in the chart approval tool.

## Expected behaviour

Charts approved after pressing the green Approve button

## Steps to reproduce

1. In the Chart Sync tool, select Source: `update-oecd-idd` and Target: `live` and press `Sync charts`
2. Go to the chart approval tool
3. Select "Approve"
4. You will see this error:
```
Failed to POST /api/suggested-chart-revisions/36619/update (404)
Error: Suggest chart revision 36619 cannot be updated with status="approved".
    at  (/home/owid/owid-grapher/adminSiteServer/apiRouter.ts:916:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
5. The same happens with Reject:
```
Failed to POST /api/suggested-chart-revisions/36619/update (404)
Error: Suggest chart revision 36619 cannot be updated with status="rejected".
    at  (/home/owid/owid-grapher/adminSiteServer/apiRouter.ts:916:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

## Screenshots

https://github.com/owid/owid-grapher/assets/63430031/53bed5f6-43b4-44d1-9135-2acf1fe96106

https://github.com/owid/owid-grapher/assets/63430031/6f480285-f40b-4572-846e-1000dbc48533

https://github.com/owid/owid-grapher/assets/63430031/0b43778a-4302-4b7c-ac28-491a4ef2dfa3

## Environment

For desktop, provide:

-   OS: macOS Sonoma 14.4.1
-   Browser Chrome
-   Version 123.0.6312.122 (Official Build) (arm64)

## Additional context

I can't remove these suggestions in the tool, because they can't be approved, rejected or flagged

**Comment by paarriagadap** [comment]
Update: After some ~30 minutes I can see the charts approved and the list in the tool empty. I don't know if there still something to check, but it was weird behaviour.

**Comment by paarriagadap** [comment]
This issue is probably related to a caching issue in the new https://admin.owid.io, because it took 30 minutes to be solved. This is discussed [here in Slack](https://owid.slack.com/archives/C46U9LXRR/p1712854547090199).

**Comment by danyx23** [comment]
@lucasrodes and @Marigold can you triage this issue and tell me if this is still relevant? Thanks!
